---
- import_playbook: "{{GRUNNER_TOP_DIR}}/ansible/playbooks/lxc/register.yml"
- import_playbook: "{{GRUNNER_TOP_DIR}}/ansible/playbooks/vars.yml"
  vars: {inc_node: "{{TEST_LXC_NAME}}"}
- hosts: "{{TEST_LXC_NAME}}"
  tasks:
    - name: test project under makina-states
      shell: |
             /bin/true
      when: "TEST_USE_MAKINASTATES"
      tags: project_test
    - name: test project without makina-states
      shell: |
             /bin/true
      when: "not (TEST_USE_MAKINASTATES)"
      tags: project_test
