---
- name: setup corpusops
  shell: |
    set -ex
    if [ ! -e {{cops_gci_cops_root}} ];then
      git clone {{cops_gci_cops_url}} {{cops_gci_cops_root}}
      {{cops_gci_cops_root}}/bin/install.sh -C
    {% if cops_gci_update %}
    else
      {{cops_gci_cops_root}}/bin/install.sh -C -s
    {% endif %}
    fi
- name: setup makina-states
  shell: |
    set -ex
    {% if cops_gci_ms_root %}
    if [ ! -e {{cops_gci_ms_root}} ];then
      git clone {{cops_gci_ms_url}} {{cops_gci_ms_root}}
      {{cops_gci_ms_root}}/bin/boot-salt2.sh -C --install-links
    {% if cops_gci_update %}
    else
      {{cops_gci_ms_root}}/bin/boot-salt2.sh -C --synchronize-code
    {% endif %}
    fi
    {% endif %}
