---
- debug: msg="OK"
  failed_when: "{{ not(cops_gci_url and cops_gci_registration_token)}}"
- {include: ./deploy_tools.yml,   tags: [runner_deploy_tools]}
- {include: ./glue.yml,           tags: [runner_glue]}
- {include: ./install_runner.yml, tags: [runner_install]}
- {include: ./registrations.yml,  tags: [runner_registrations]}
- {include: ./services.yml,       tags: [runner_services]}
