---
- listen: restart_cops_gci_service
  shell: systemctl daemon-reload
  when: "(cops_gci_activated and corpusops_vars.has_services_manager and (ansible_service_mgr == 'systemd'))"
- listen: restart_cops_gci_service
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{item}}"
  with_items: "{{[cops_gci_service]}}"
  when: "(cops_gci_activated and corpusops_vars.has_services_manager and (ansible_service_mgr == 'systemd'))"
- listen: restart_cops_gci_service
  cops_service:
    state: restarted
    name: "{{item}}"
  with_items: "{{[cops_gci_service]}}"
  when: "(cops_gci_activated and corpusops_vars.has_services_manager and (ansible_service_mgr != 'systemd'))"
