---
- hosts: all
  vars:
    ansible_connection: local
  roles:
    - role: "corpusops.roles/vars"
    - role: "cops_gci_vars"
- hosts: all
  tasks:
    - debug:
        msg: "{{cops_gci_vaults_passwords.get(
            inventory_hostname,{})}}"
      register: vaults
    - copy:
        dest: "~/.ansiblevaultpassword.{{item.key}}"
        content: "{{item.value}}"
        mode: "0600"
      with_dict: "{{vaults.msg}}"
