---
- hosts: all
  vars:
    lxc_container_name: "{{lxc}}"
  roles:
    - role: corpusops.saltcall
    - role: corpusops.lxc_register
- hosts: "{{lxc}}"
  tasks:
    - name: create project
      shell: |
        if [ ! -e /srv/projects/mysql ];then
          /srv/makina-states/bin/salt-call --retcode-passthrough\
            mc_project.init_project mysql
        fi
    - name: pillar
      copy:
        dest: /srv/projects/mysql/pillar/init.sls
        content: |
          ---
          makina-states.services.mysql.root_password: mysql
          makina-states.services.mysql.bind_address: 127.0.0.1
          makina-projects.mysql:
            api_version: '2'
            data:
              pma_enabled: false
              backup_disabled: true
              databases:
               {% for i in [0,1,2,3,4,5,6,7,8,9]%}
               - {db{{i}}: {password: "db{{i}}", user: "db{{i}}"}}
               {%endfor%}
    - name: code
      shell: |
        cd /srv/projects/mysql/project
        git stash
        git remote rm g || /bin/true
        git remote add g https://github.com/makinacorpus/corpus-mysql.git
        git fetch --all
        git reset --hard g/master
    - name: re config mysql - first time may fail
      saltcall:
        function: mc_project.deploy 
        args: "only=install,fixperms mysql"
      register: mysql_install_1
      failed_when: False
    - name: re config mysql - first time may fail
      saltcall:
        function: mc_project.deploy 
        args: "only=install,fixperms mysql"
      register: mysql_install_2
      when: "{{mysql_install_1.msg.retcode!=0}}"
