{%- set cfg = salt['mc_project.get_configuration'](cfg) %}
{%- set data = cfg.data %}
{%- set r=data.runner_config %}
{%- set rs=data.runner_config.runners %}
{%- set ssh=data.runner_config.runners.get('ssh', {}) %}

concurrent = {{r.concurrent}}
check_interval = {{r.check_interval}}

[[runners]]
  name = "{{rs.name}}"
  url = "{{rs.url}}"
  token = "{{rs.token}}"
  executor = "{{rs.executor}}"
  builds_dir = "{{data.builds_dir}}"
  cache_dir = "{{data.cache_dir}}"
  {% if rs.executor in ['ssh'] %}
  [runners.ssh]
  {% for i in ['user', 'host', 'identity_file'] %}
    {% if ssh.get(i) %}{{i}} = "{{ssh[i]}}"{%endif%}
  {% endfor %}
  {% endif %}
  [runners.cache]
