---
# Run project setup
- include: "{{GRUNNER_TOP_DIR}}/ansible/playbooks/vars.yml"
  vars: {inc_node: "{{test_node|default('all')}}"}
- hosts: "{{test_node|default('all')}}"
  tasks:
    - name: render pillar from ansible vault
      template:
        src: "{{GRUNNER_TOP_DIR}}/ansible/playbooks/templates/pillar"
        dest: "{{ms_pillar}}"
        force: true
        mode: "0644"
      when: "(TEST_USE_MAKINASTATES|bool and ((vars.get('makinastates_pillar', '')|length) > 0))"
      tags: project_setup,project_setup_ms
    - name: build project
      shell: |
        salt-call -l {{TEST_SALTCALL_LOGLEVEL}} --retcode-passthrough \
          mc_project.deploy {{ms_project_name}} only=install,fixperms
      when: "TEST_USE_MAKINASTATES"
      tags: project_setup,project_setup_ms
