---
# Run project setup
- include: "{{GRUNNER_TOP_DIR}}/ansible/playbooks/vars.yml"
  vars: {inc_node: "{{test_node}}"}
- hosts: "{{test_node}}"
  tasks:
    - name: test if we have pillar sample file
      stat: {path: "{{ms_pillar_test}}"}
      register: project_setup_pillar_test
      failed_when: false
      when: "{{TEST_USE_MAKINASTATES}}"
      tags: project_setup,project_test_ms
    - name: copy pillar test file
      copy:
        src: "{{ms_pillar_test}}"
        dest: "{{ms_pillar}}"
        force: true
        remote_src: true
        mode: "0644"
      when: "{{TEST_USE_MAKINASTATES and project_setup_pillar_test.stat.exists}}"
      tags: project_setup,project_test_ms
    - name: build project
      shell: |
        salt-call -l {{TEST_SALTCALL_LOGLEVEL}} --retcode-passthrough \
          mc_project.deploy {{ms_project_name}} only=install,fixperms
      when: "{{TEST_USE_MAKINASTATES}}"
      tags: project_setup,project_setup_ms
