---
# Run project test, this is this playbook you want to override in your
# project
- include_playbook: "{{GRUNNER_TOP_DIR}}/ansible/playbooks/vars.yml"
  vars: {inc_node: "{{test_node|default('all')}}"}
- hosts: "{{test_node|default('all')}}"
  tasks:
    - name: test project under makina-states
      shell: |
             /bin/true
      when: "TEST_USE_MAKINASTATES"
      tags: project_test
    - name: test project without makina-states
      shell: |
             /bin/true
      when: "not (TEST_USE_MAKINASTATES)"
      tags: project_test
